version: '3'
services:
  app:
    build: ./docker/app
    container_name: kotlin-playground
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    command: ./gradlew bootRun
  mysql:
    build:
      context: ./docker/mysql
      dockerfile: Dockerfile
    container_name: mysql
    volumes:
      - ./mysql/data:/var/lib/mysql
    user: 1000:1000
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: playground